### PR TITLE
Fix macOS build

### PR DESCRIPTION
**Pull request by cdlhub**

### CODE REVIEW

**Comment by cdlhub** [comment]
@bmatharu Any decision on this?

**Comment by bmatharu** [comment]
There is already an option at the .configure state  --enable-osx=yes

**Comment by bmatharu** [comment]
This should allow you to build on osx - I'm not a mac user so I need to check with someone who is to make sure this still works.

**Comment by mpinkerton-oasis** [comment]
@sr-murthy any thoughts on this, as a mac user?

**Comment by sr-murthy** [comment]
There have been changes in ktools to support building on OS X, and I think it should be fine now, providing the user has reasonably up-to-date version of the Xcode command line tools, which is the OS X command line package add-on that contains compilers such as GCC/Clang and other command line utilities that would be required in the building of ktools.

So for OS X I would first recommend an upgrading of the Xcode command line tools (using either `xcode-select --install` or downloading the latest version from developer.apple.com. Then just follow the instructions in the ktools repo. I run the following chained command from the base of the ktools repo

    ./configure --enable-osx && make && make check && make install

**Comment by sr-murthy** [comment]
There have been changes in ktools to support building on OS X, and I think it should be fine now, providing the user has a reasonably up-to-date version of the Xcode command line tools, which is the OS X command line package add-on that contains compilers such as GCC/Clang and other command line utilities that would be required in the building of ktools.

So for OS X I would first recommend an upgrading of the Xcode command line tools (using either `xcode-select --install` or downloading the latest version from [developer.apple.com](developer.apple.com). Then just follow the instructions in the ktools repo. I run the following chained command from the base of the ktools repo

    ./configure --enable-osx && make && make check && make install

**Comment by cdlhub** [comment]
I still have an error, which should be solved by this PR. See [ktgetmem.cpp diff](https://github.com/OasisLMF/ktools/pull/30/files).

**OS environment**

- macOS 10.13.6
- xcode-select version 2349

**Step to reproduce**

```sh
./autogen.sh 
./configure --enable-osx && make && make check && make install
```

**Expected results**

Successful build.

**Actual results**

```txt
checking for a BSD-compatible install... /usr/local/opt/coreutils/libexec/gnubin/install -c
checking whether build environment is sane... yes
...
ktgetmem.cpp:5:10: fatal error: 'sys/sysinfo.h' file not found
#include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [ktgetmem.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by bmatharu** [comment]
Thanks Camille we've checked that in so its ignored on OSX.

**Comment by sr-murthy** [comment]
@cdlhub That error was just fixed. Please update your local ktools `master` and try the build again.

**Comment by cdlhub** [comment]
@sr-murthy That worked. Thanks.

**Comment by sr-murthy** [comment]
I've just realised you made the same change. I thought this was an issue, not a PR, so I didn't see your proposed changes.

**Pull request closed without merging**
