### PR TITLE
Remove unrequired lines in getmodel output

### PR DESCRIPTION
**Pull request by hchagani-oasislmf**
Introduce an escape condition in for loop to ensure that once cumulative probability reaches 1.0, later damage bin indexes are ignored in cases where footprint file does not have hazard intensity uncertainty. The output is now:

```
$ hexdump ./static/footprint.bin.z | head -1
0000000 003a 0000 0000 0000 9c78 cd4d 2eb9 6184
$ echo 1139 | evetobin -n | getmodel | cdftocsv | head -13
event_id,areaperil_id,vulnerability_id,bin_index,prob_to,bin_mean
1139,36,2,1,0.638000,0.000000
1139,36,2,2,0.814000,0.050000
1139,36,2,3,0.902000,0.150000
1139,36,2,4,0.955000,0.250000
1139,36,2,5,0.996000,0.350000
1139,36,2,6,1.000000,0.450000
1139,36,5,1,0.638000,0.000000
1139,36,5,2,0.814000,0.050000
1139,36,5,3,0.902000,0.150000
1139,36,5,4,0.955000,0.250000
1139,36,5,5,0.996000,0.350000
1139,36,5,6,1.000000,0.450000
```

### CODE REVIEW

**Comment by hchagani-oasislmf** [comment]
Adding you as a reviewer @johcarter. Toggled the no hazard uncertainty flag to in the header of `static/footprint.bin` and compared outputs. There are some differences, but they appear to be floating point errors. For example:

```
diff output_0_168/gul_S1_aalcalc.csv output_1_168/gul_S1_aalcalc.csv
2,3c2,3
< 1,1,235819.241313,594470.165426,3400000.000000
< 1,2,230784.911049,591912.830039,3400000.000000
---
> 1,1,235819.239000,594470.163407,3400000.000000
> 1,2,230784.914008,591912.835002,3400000.000000
```

Interestingly, we see similar discrepancies in `develop`. For example:

```
diff -r output_0/gul_S1_aalcalc.csv output_1/gul_S1_aalcalc.csv
2,3c2,3
< 1,1,235819.241313,594470.165426,3400000.000000
< 1,2,230784.911049,591912.830039,3400000.000000
---
> 1,1,235819.239000,594470.163407,3400000.000000
> 1,2,230784.914008,591912.835002,3400000.000000
```

I've attached a list of differences. I'll take a look through them too: I suspect that they are all floating point errors, but two pairs of eyes are better than one.
[168_diff.txt](https://github.com/OasisLMF/ktools/files/5820308/168_diff.txt)

**Comment by hchagani-oasislmf** [comment]
The outputs from `develop` and `fix/168-unrequired-lines-no-hazard-intensity-uncertainty` when using a `footprint.bin` file with no hazard uncertainty match. It looks fine to me: I think we can merge into `develop` @johcarter.

**Comment by johcarter** [comment]
please could you send me the before and after output folders @hchagani-oasislmf ? its difficult to eyeball in the txt file. thank you

**Comment by hchagani-oasislmf** [comment]
Hi @johcarter. As requested, please find a zip file containing all the output data in the following configurations:

- output_0/ - develop branch, no hazard uncertainty flag = 0 in footprint.bin
- output_0_168/ - fix/168-unrequired-lines-no-hazard-intensity-uncertainty branch, no hazard uncertainty flag = 0 in footprint.bin
- output_1/ - develop branch, no hazard uncertainty flag = 1 in footprint.bin
- output_1_168/ - fix/168-unrequired-lines-no-hazard-intensity-uncertainty branch, no hazard uncertainty flag = 1 in footprint.bin

I also witnessed the different ordering of events. I assume this is a compiler issue that will hopefully become a concern of the past when we merge `fix/119-deterministic-event-id-shuffle` into `develop`. Directories `output_0/sort/` and `output_0_168/sort/`
 contain files sorted by event ID.

[ktools-pr179-output.zip](https://github.com/OasisLMF/ktools/files/5829361/ktools-pr179-output.zip)

**Comment by johcarter** [comment]
thanks. I see it is the use of the -n flag causing the floating point errors (the different calculation logic to compute the cumulative probability thresholds in cdfs results in floating point errors), and not the fix which does not cause any floating point errors in results at all. Yes I agree this is fine to merge, thank you @hchagani-oasislmf

**Pull request merged**
