### PR TITLE
Refactor fmcalcdoit() v3.2.2

### PR DESCRIPTION
**Pull request by cdl-clgx**
- I made the logic more comprehensive.
- No performance changes.
- Based on version 3.2.2
- No changes observed in output with my own set of exposure data.

**Please, run your own set of tests.**

**Note:** diff is hard to read, although direct review of the code will help better to understand changes.

### CODE REVIEW

**Comment by johcarter** [comment]
make check fails 36 checksums and ktest/ftest/ runtests fails 126 checksums, i'm afraid. we can't merge until all checks pass

**Comment by cdl-clgx** [comment]
Ok, I'll check why the build failed.
Other than that, is there a way to check why numbers are not the same?

**Comment by johcarter** [comment]
no i'm afraid not. I tend rerun all these tests after every small change so that i know what broke it.

**Comment by johcarter** [comment]
for make check you can run make check in ktools_develop and compare the output in ktest/testout with your own.

**Comment by cdl-clgx** [comment]
I wish I asked my question earlier :-/ 
Next time I won't forget to run `make check` more often.
I may try to go back in history to see where I broke results.

**Comment by johcarter** [comment]
sorry ... Also do please use ktest/ftest. this one has 60 fmcalc tests, make check only has 1 fmcalc test.

**Comment by cdl-clgx** [comment]
I can't find `ktest/ftest`. Should I build it somehow?

**Comment by johcarter** [comment]
https://github.com/OasisLMF/ktest

it runs on your installed exes, so run  after make install in ktools

cd ftest
sh runtests.sh

**Comment by cdl-clgx** [comment]
Got it, thanks.

**Comment by johcarter** [comment]
you're welcome

**Comment by sambles** [comment]
Closed because no update since March

**Pull request closed without merging**
